version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  engine:
    build:
      context: .
      dockerfile: engine-core/Dockerfile
    container_name: matching-engine
    env_file:
      - .env.dev
    ports:
      - "9999:9999"
      - "9998:9998"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4g

  kafka-adapter:
    build:
      context: .
      dockerfile: adapter-kafka/Dockerfile
    container_name: kafka-adapter
    depends_on:
      - engine
      - kafka
    env_file:
      - .env.dev
    restart: on-failure

  ws-gateway:
    build:
      context: .
      dockerfile: adapter-ws/Dockerfile
    container_name: ws-gateway
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    restart: on-failure

  order-generator:
    build:
      context: .
      dockerfile: order-generator/Dockerfile
    container_name: order-generator
    depends_on:
      - engine
    env_file:
      - .env.dev
    restart: on-failure

  audit-volume:
    image: busybox:latest
    container_name: audit-volume
    volumes:
      - ./audit/reports:/audit
    command: ["sh", "-c", "tail -f /dev/null"]
