server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    static_configs:
      - targets: [localhost]
        labels:
          job: containerlogs
          # docker.sock api 연동 대신 containers 폴더 하위 log 파일을 직접 감시
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - regex:
          # 로그 파일의 절대경로(__path__ 또는 filename)에서 컨테이너 ID 추출하여 라벨로 매핑
          source: filename
          expression: "/var/lib/docker/containers/(?P<container_id>[a-f0-9]+)/.*\\.log"
      - labels:
          container_id:
