spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/exchange}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: none

ethereum:
  rpc-url: ${EVM_RPC_URL:http://localhost:8545}
  rpc-url-docker: ${EVM_RPC_URL_DOCKER:http://localhost:8545}
  private-key: ${EVM_PRIVATE_KEY:0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d}
